export const galleyActionTypes = {
    GET_GALLERY :"GET_GALLERY",
    GET_GALLERY_SUCCESS:"GET_GALLERY_SUCCESS",
    GET_GALLERY_FAIL:"GET_GALLERY_FAIL",
    UPLOAD_GALLERY_IMAGE :"UPLOAD_GALLERY_IMAGE",
    UPLOAD_GALLERY_IMAGE_SUCCESS:"UPLOAD_GALLERY_IMAGE_SUCCESS",
    UPLOAD_GALLERY_IMAGE_FAIL:"UPLOAD_GALLERY_IMAGE_FAIL",
    DELETE_GALLERY_IMAGE :"DELETE_GALLERY_IMAGE",
    DELETE_GALLERY_IMAGE_SUCCESS:"DELETE_GALLERY_IMAGE_SUCCESS",
    DELETE_GALLERY_IMAGE_FAIL:"DELETE_GALLERY_IMAGE_FAIL"
}