export const notificationsActionTypes = {
    GET_ALL_NOTIFICATIONS: "GET_ALL_NOTIFICATIONS",
    GET_ALL_NOTIFICATIONS_SUCCESS: "GET_ALL_NOTIFICATIONS_SUCCESS",
    GET_ALL_NOTIFICATIONS_FAIL: "GET_ALL_NOTIFICATIONS_FAIL",
    UPDATE_NOTIFICATIONS: "UPDATE_NOTIFICATIONS",
    UPDATE_NOTIFICATIONS_SUCCESS: "UPDATE_NOTIFICATIONS_SUCCESS",
    UPDATE_NOTIFICATIONS_FAIL: "UPDATE_NOTIFICATIONS_FAIL"
}