export const verifyOtpActionType = {
    REQUEST_VERIFY_OTP : "REQUEST_VERIFY_OTP",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    VERIFY_OTP_FAIL: "VERIFY_OTP_FAIL",
    VERIFY_OTP_FOR_NEW_NUMBER_REQUEST:"VERIFY_OTP_FOR_NEW_NUMBER_REQUEST",
    VERIFY_OTP_FOR_NEW_NUMBER_SUCCESS:"VERIFY_OTP_FOR_NEW_NUMBER_SUCCESS",
    VERIFY_OTP_FOR_NEW_NUMBER_FAILURE:"VERIFY_OTP_FOR_NEW_NUMBER_FAILURE"

}