export const jobsActionTypes = {
    GET_JOBS :"GET_JOBS",
    GET_JOBS_SUCCESS:"GET_JOBS_SUCCESS",
    GET_JOBS_FAIL:"GET_JOBS_FAIL",
    UPDATE_JOB :"UPDATE_JOB",
    UPDATE_JOB_SUCCESS:"UPDATE_JOB_SUCCESS",
    UPDATE_JOB_FAIL:"UPDATE_JOB_FAIL",
    REJECT_JOB :"REJECT_JOB",
    REJECT_JOB_SUCCESS:"REJECT_JOB_SUCCESS",
    REJECT_JOB_FAIL:"REJECT_JOB_FAIL",
    GET_JOB_DETAIL:"GET_JOB_DETAIL",
    GET_JOB_DETAIL_SUCCESS:"GET_JOB_DETAIL_SUCCESS",
    GET_JOB_DETAIL_FAIL:"GET_JOB_DETAIL_FAIL"
}